--3
SELECT * FROM TB_BOOK;
SELECT * FROM TB_WRITER;
SELECT * FROM TB_PUBLISHER;
SELECT * FROM TB_BOOK_AUTHOR;

SELECT BOOK_NO, BOOK_NM
FROM TB_BOOK
WHERE LENGTH (BOOK_NM)>=25; 

--4
SELECT WRITER_NM, OFFICE_TELNO, HOME_TELNO, MOBILE_NO
FROM TB_WRITER
WHERE MOBILE_NO LIKE '019%'
ORDER BY WRITER_NM ASC;

--6
SELECT MAINCTG, COUNT(*)
FROM TB_BOOK
WHERE MAINCTG IS NOT NULL
GROUP BY MAINCTG;


