--SELECT 기본문제
--1번
SELECT JOB_NAME
FROM JOB;

--2번
SELECT *
FROM DEPARTMENT;

--3
SELECT EMP_NAME, EMAIL, PHONE, HIRE_DATE
FROM EMPLOYEE;

--4
SELECT HIRE_DATE, EMP_NAME, SALARY
FROM EMPLOYEE;

--5
SELECT EMP_NAME, SAL_LEVEL
FROM EMPLOYEE
WHERE SALARY>2500000;

--6
SELECT EMP_NAME, PHONE
FROM EMPLOYEE
WHERE JOB_CODE='J3' AND SALARY>3500000;

--1
SELECT EMP_NAME, SALARY, (SALARY+SALARY*BONUS)*12 총수령액, ((SALARY+SALARY*BONUS)*12)-(SALARY*0.03) 실수령액
FROM EMPLOYEE;

--2
SELECT EMP_NAME, TRUNC(SYSDATE)-HIRE_DATE 근무일수
FROM EMPLOYEE;

--3
SELECT EMP_NAME, SALARY, BONUS
FROM EMPLOYEE
WHERE TRUNC(SYSDATE)-HIRE_DATE > 7000;

--4
SELECT EMP_NAME, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE DEPT_CODE='D6' AND SALARY>2000000;

--5
SELECT EMP_NAME
FROM EMPLOYEE
WHERE NOT DEPT_CODE='D6';

--6
SELECT DISTINCT SAL_LEVEL
FROM EMPLOYEE
WHERE NOT JOB_CODE='J1';

--7
SELECT EMP_NAME
FROM EMPLOYEE
WHERE EMP_NAME LIKE '_옹_';

--8
SELECT EMP_NAME, EMAIL
FROM EMPLOYEE
WHERE EMAIL LIKE '____A_%' ESCAPE 'A';

--1
SELECT EMP_NAME
FROM EMPLOYEE
WHERE EMP_NAME LIKE '%연';

--2
SELECT EMP_NAME, PHONE
FROM EMPLOYEE
WHERE NOT PHONE LIKE '010%';

--3
SELECT *
FROM EMPLOYEE
WHERE EMAIL LIKE '____A_%' ESCAPE 'A' AND DEPT_CODE='D9' OR DEPT_CODE='D6' AND SALARY>2700000
